SELECT * FROM TB_DEPARTAMENTO;
SELECT * FROM TB_FUNCIONARIO;
SELECT * FROM TB_LOCALIZACOES_DEPARTAMENTOS;
SELECT * FROM TB_PROJETO;
SELECT * FROM TB_TRABALHA_EM;
SELECT * FROM TB_DEPENDENTE;

SELECT * FROM TB_TRABALHA_EM WHERE NUMERO_PROJETO = '1' AND HORAS = '33';
SELECT * FROM TB_TRABALHA_EM WHERE NUMERO_PROJETO = 1 OR NUMERO_PROJETO = 2;